//Error codes TimeHarp THLIB v6.1, February 2009

#define ERROR_NONE					  0

#define ERROR_DEVICE_OPEN_FAIL		 -1
#define ERROR_DEVICE_BUSY			 -2
#define ERROR_DEVICE_HEVENT_FAIL	 -3
#define ERROR_DEVICE_CALLBSET_FAIL	 -4
#define ERROR_DEVICE_BARMAP_FAIL	 -5
#define ERROR_DEVICE_CLOSE_FAIL		 -6
#define ERROR_DEVICE_RESET_FAIL		 -7
#define ERROR_DEVICE_VERSION_FAIL	 -8
#define ERROR_DEVICE_VERSION_MISMATCH -9

#define ERROR_INSTANCE_RUNNING		-16
#define ERROR_INVALID_ARGUMENT		-17
#define ERROR_INVALID_MODE			-18
#define ERROR_INVALID_OPTION		-19
#define ERROR_INVALID_MEMORY		-20
#define ERROR_INVALID_RDATA			-21
#define ERROR_NOT_INITIALIZED		-22
#define ERROR_NOT_CALIBRATED		-23
#define ERROR_DMA_FAIL				-24
#define ERROR_XTDEVICE_FAIL			-25

#define ERROR_CALIB_MAXRET_FAIL		-32
#define ERROR_CALIB_REGINIT_FAIL	-33
#define ERROR_CALIB_CVALERRBIT		-34
#define ERROR_CALIB_MVALERRBIT		-35
#define ERROR_CALIB_MFIT_FAIL		-36
#define ERROR_CALIB_MINVALID		-37

#define ERROR_SCX_NOT_PRESENT		-48
#define ERROR_SCX_NOT_ENABLED		-49
#define ERROR_SCX_RESET_FAIL		-50
#define ERROR_SCX_NOT_ACTIVE		-51
#define ERROR_SCX_STILL_ACTIVE		-52
#define ERROR_SCX_GOTOXY_FAIL		-53
#define ERROR_SCX_SCPROG_FAIL		-54

#define ERROR_HARDWARE_F01			-64
#define ERROR_HARDWARE_F02			-65
#define ERROR_HARDWARE_F03			-66
#define ERROR_HARDWARE_F04			-67
#define ERROR_HARDWARE_F05			-68
#define ERROR_HARDWARE_F06			-69
#define ERROR_HARDWARE_F07			-70
#define ERROR_HARDWARE_F08			-71
#define ERROR_HARDWARE_F09			-72
#define ERROR_HARDWARE_F10			-73
#define ERROR_HARDWARE_F11			-74
#define ERROR_HARDWARE_F12			-75
#define ERROR_HARDWARE_F13			-76
#define ERROR_HARDWARE_F14			-77
#define ERROR_HARDWARE_F15			-78

